version: '2'
services:     
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /home/usenet/config/nzbget:/config
            - /home/usenet/appdata/nzbget:/downloads
            - /storage/downloads/usenet:/complete
        ports:
            - 6789:6789
        env_file: uidgid.env
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /home/usenet/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /storage/downloads/usenet:/complete
            - /storage/tvshows:/tv
        ports:
            - 8989:8989
        env_file: uidgid.env
        depends_on:
            - nzbget
        restart:  unless-stopped
        
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /home/usenet/config/radarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /storage/downloads/usenet:/complete
            - /storage/movies:/movies      
        ports:
            - 7878:7878        
        env_file: uidgid.env
        depends_on:
            - nzbget
        restart: unless-stopped
        
    lazy:
        image: linuxserver/lazylibrarian
        container_name: lazy
        volumes:
            - /home/usenet/config/lazy:/config
            - /storage/downloads/usenet/books:/downloads
            - /storage/books:/books
        ports:
            - 5299:5299
        environment:
            - TZ=America/New_York
        env_file: uidgid.env
        depends_on:
            - nzbget
        restart: unless-stopped
        
    plex:
        image: plexinc/pms-docker
        container_name: plex
        volumes:
            - /home/usenet/config/plex:/config
            - /storage/transcodes:/transcode
            - /storage/tvshows:/data/tvshows
            - /storage/movies:/date/movies
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=America/New_York
            - PLEX_CLAIM=CLAIM-568MKGQUNQYZDQMA95NN
            - ADVERTISE_IP=http://192.168.1.41:32400/
            - PLEX_UID=200
            - PLEX_GID=200
        hostname: PlexServer
        restart: unless-stopped

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - /home/usenet/config/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - /home/usenet/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        restart:  unless-stopped

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /home/usenet/config/nzbhydra:/config
            - /storage/downloads/usenet:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        restart:  unless-stopped

    organizr:
        image: lsiocommunity/organizr
        container_name: organizr
        volumes:
            - /home/usenet/config/organizr:/config
        ports:
            - 80:80
        env_file: uidgid.env
        restart:  unless-stopped
        
    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - /home/usenet/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        restart: unless-stopped
        
    beets:
    image: linuxserver/beets
    container_name: beets
    hostname: beets
    environment:
      - PUID=108
      - PGID=115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /.dockerconfig/beets:/config
      - /media/complete/audio:/downloads
      - /media/music:/music
