version: '2'
services:
    traefik:
        image: traefik
        command: --web --docker --docker.domain=docker.localhost --docker.watch --logLevel=DEBUG --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS:tls/wildcard.bleemeo.work.crt,tls/wildcard.bleemeo.work.key' --defaultEntryPoints='http,https' --accessLogsFile='log/access.log'
        network_mode: "host"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
         ports:
            - "80:80"
            - "8080:8080"
         restart: unless-stopped
         
    plex:
        image: plexinc/pms-docker
        container_name: plex
        volumes:
            - <config_directory>/config/plex:/config
            - <path/to/transcode/temp>:/transcode
            - <path/to/media>:/data
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=<timezone>
            - PLEX_CLAIM=<claimToken>
            - ADVERTISE_IP=http://<hostIPAddress>:32400/
        hostname: <hostname> 
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - <config_directory>/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /data_directory_path/TV:/tv
            - /data_directory_path/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        labels:
            - traefik.backend=sonarr
            - traefik.frontend.rule=Host:ci.bleemeo.work
            - traefik.port=8989
        restart:  unless-stopped

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - <config_directory>/config/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - <config_directory>/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=plexpy
        restart:  unless-stopped

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - <config_directory>/config/nzbhydra:/config
            - /data_directory_path/Downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=nzbhydra
        restart:  unless-stopped

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - <config_directory>/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=muximux
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - <config_directory>/config/radarr:/config
            - /data_directory_path/Movies:/movies
            - /data_directory_path/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=radarr
            - VIRTUAL_PORT=7878
        restart: unless-stopped

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - <config_directory>/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=ombi
        restart: unless-stopped

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - <config_directory>/config/nzbget:/config
            - <usenet_download_dir>/Downloads/complete:/complete
            - /data_directory_path/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=nzbget
        restart: unless-stopped
        
    portainer:
        image: portainer/portainer
        container_name: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - <config_directory>/config/portainer:/data
        ports:
            - 9000:9000
        restart: unless-stopped
