version: '2'
services:
    nginx-proxy:
        image: theit8514/nginx-proxy-subdirectory:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    plex:
        image: plexinc/pms-docker
        container_name: plex
        volumes:
            - <config_directory>/config/plex:/config
            - <path/to/transcode/temp>:/transcode
            - <path/to/media>:/data
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        environment:
            - TZ=<timezone>
            - PLEX_CLAIM=<claimToken>
            - ADVERTISE_IP=http://<hostIPAddress>:32400/
        hostname: <hostname> 
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - <config_directory>/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /data_directory_path/TV:/tv
            - /data_directory_path/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=sonarr
        restart:  unless-stopped

    plexpy:
        image: linuxserver/plexpy
        container_name: plexpy
        volumes:
            - <config_directory>/config/plexpy:/config
            - /etc/localtime:/etc/localtime:ro
            - <config_directory>/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        ports:
            - 8181:8181
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=plexpy
        restart:  unless-stopped

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - <config_directory>/config/nzbhydra:/config
            - /data_directory_path/Downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=nzbhydra
        restart:  unless-stopped

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - <config_directory>/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=muximux
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - <config_directory>/config/radarr:/config
            - /data_directory_path/Movies:/movies
            - /data_directory_path/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=radarr
            - VIRTUAL_PORT=7878
        restart: unless-stopped

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        volumes:
            - <config_directory>/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=ombi
        restart: unless-stopped

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - <config_directory>/config/nzbget:/config
            - <usenet_download_dir>/Downloads/complete:/complete
            - /data_directory_path/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - NGINX_PROXY_SUBDIRECTORY=nzbget
        restart: unless-stopped
